worker_processes auto;
events {
    worker_connections 1024;
}
http {
    server {
        listen 8080;
        location / {
            # Dito ituturo sa IP ng VPS mo
            proxy_pass http://167.172.69.123:80; 
            
            # Mahalaga para sa WebSocket/VPN connection
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            
            # Iwas sa 504 Gateway Timeout
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}
